---
- name: "postinstall | link RHEL to subscription manager"
  ansible.builtin.import_tasks: rhel/subscription.yml
  when: ansible_distribution == 'RedHat'

- name: perform debian based specific tasks
  block:
    - name: import apt tasks
      ansible.builtin.import_tasks: debian/apt.yml

    - name: import debian packages install
      ansible.builtin.import_tasks: debian/pkg_install.yml
  when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'

- name: perform rhel based specific tasks
  block:
    - name: import yum tasks
      ansible.builtin.import_tasks: rhel/yum.yml

    - name: import RedHat packages install
      ansible.builtin.import_tasks: rhel/pkg_install.yml
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'RedHat' or
        ansible_distribution == 'Rocky'

- name: import common package install
  ansible.builtin.import_tasks: pkg_install.yml
