---
- name: "postinstall | link RHEL to subscription manager"
  ansible.builtin.import_tasks: rhel/subscription.yml
  when: ansible_distribution == 'RedHat'

- name: "perform debian based specific tasks"
  block:
    - name: "INCLUDE => DEBIAN | postinstall | apt tasks"
      ansible.builtin.import_tasks: debian/apt.yml

    - name: "INCLUDE => DEBIAN | postinstall | debian packages install"
      ansible.builtin.import_tasks: debian/pkg_install.yml
  when: ansible_os_family == 'Debian'

- name: "perform rhel based specific tasks"
  block:
    - name: "INCLUDE => RHEL | postinstall | yum tasks"
      ansible.builtin.import_tasks: rhel/yum.yml

    - name: "INCLUDE => RHEL | postinstall | RedHat packages install"
      ansible.builtin.import_tasks: rhel/pkg_install.yml
  when: ansible_os_family == 'RedHat'

- name: "INCLUDE => COMMON | postinstall | package install"
  ansible.builtin.import_tasks: pkg_install.yml
