---
- name: "Postinstall | Install common packages"
  tags:
    - install
  block:
    - name: "Postinstall | pkg_install | Install disk collection tools"
      ansible.builtin.package:
        state: present
        name: "{{ v_common['disk_pkg'] }}"

    - name: "Postinstall | pkg_install | Install net collection tools"
      ansible.builtin.package:
        state: present
        name: "{{ v_common['net_pkg'] }}"

    - name: "Postinstall | pkg_install | Install sys collection tools"
      ansible.builtin.package:
        state: present
        name: "{{ v_common['sys_pkg'] }}"
      notify: "Update mlocate database"

    - name: "Postinstall | pkg_install | Install shell"
      ansible.builtin.package:
        state: present
        name: "{{ v_common['shell_pkg'] }}"

    - name: "Postinstall | pkg_install | Install security collection tools"
      ansible.builtin.package:
        state: present
        name: "{{ v_common['security_pkg'] }}"
