---
# @meta author: Vincent FRICOU
# @meta description: Linux servers OS postinstallation and updates management
# @tag install # Perform packages installations on any supported OS and initial registration for RHEL OS
# @tag fullupgrade # Perform full upgrade on any supported OS
# @tag safeupgrade # Perform full upgrade without kernel on any supported OS
# @tag bugsecupgrade # (RHEL only) Perform bugfix and security update
# @tag subscription # (RHEL only) Perform subscription update

- name: "Import validator tasks"
  ansible.builtin.import_tasks: validator/main.yml
  tags:
    - always

- name: "Import postinstall tasks"
  ansible.builtin.import_tasks: postinstall/main.yml

- name: "Import postinstall tasks"
  ansible.builtin.import_tasks: pamd/main.yml
  when: pamd_config
  tags:
    - always
