---
# @meta author: Vincent FRICOU
# @meta description: Linux servers OS postinstallation and updates management
# @tag install # Perform packages installations on any supported OS
# @tag fullupgrade # Perform full upgrade on any supported OS
# @tag safeupgrade # Perform full upgrade without kernel on any supported OS
# @tag bugsecupgrade # (RHEL only) Perform bugfix and security update
# @tag security # Perform only security configuration tasks
# @tag configure # Perform configurations tasks

- name: "import validator tasks"
  import_tasks: validator/check_os.yml
  tags:
    - always

- name: "import postinstall tasks"
  import_tasks: postinstall/main.yml

- name: "perform some services post configurations"
  block:
    - name: "import postinstall tasks"
      import_tasks: pamd/main.yml
      when: pamd_config

    - name: "import openssh tasks"
      import_tasks: openssh/main.yml
      when: openssh_config
  tags:
    - install
    - security
    - configure
