---
# @meta author: Vincent FRICOU
# @meta description: Linux servers OS postinstallation and updates management
# @tag install # Perform packages installations on any supported OS
# @tag fullupgrade # Perform full upgrade on any supported OS
# @tag safeupgrade # Perform full upgrade without kernel on any supported OS
# @tag bugsecupgrade # (RHEL only) Perform bugfix and security update

- name: "import validator tasks"
  import_tasks: validator/check_os.yml
  tags:
    - always

- name: "import postinstall tasks"
  import_tasks: postinstall/main.yml

- name: "import postinstall tasks"
  import_tasks: pamd/main.yml
  when: pamd_config
  tags:
    - always
