---
- name: restart auditd
  service:
    state: started
    enabled: yes
    name: auditd

- name: update mlocate database
  command: updatedb

- name: restart openssh
  service:
    name: sshd
    enabled: yes
    state: restarted
