---
- name: "Pamd | Redhat based os - Update pamd permission for wheel group"
  ansible.builtin.replace:
    path: /etc/pam.d/su
    regexp: '#(\s*)auth(\s+|\t+)sufficient(\s+|\t+)pam_wheel.so(\s+|\t+)trust(\s+|\t+)use_uid'
    replace: 'auth sufficient pam_wheel.so trust use_uid'
  when: ansible_os_family == 'RedHat'

- name: "Pamd | Debian based os - Update pamd permission for wheel group"
  ansible.builtin.replace:
    path: /etc/pam.d/su
    regexp: '#(\s*)auth(\s+|\t+)sufficient(\s+|\t+)pam_wheel.so(\s+|\t+)trust'
    replace: 'auth sufficient pam_wheel.so trust'
  when: ansible_os_family == 'Debian'
