---
- name: "postinstall | debian | apt | update local cache"
  apt:
    update_cache: yes
    cache_valid_time: 7200
  tags:
    - always

- name: "postinstall | debian | apt | get packages facts"
  package_facts:
  tags:
    - always

- name: "postinstall | debian | apt | lock kernel packages"
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - "{{ ansible_facts.packages.keys()|list | map('regex_search', v_debian['exclusions']) | select('string') }}"
  tags:
    - safeupgrade

- name: "postinstall | debian | apt | unlock kernel packages"
  dpkg_selections:
    name: '{{ item }}'
    selection: install
  with_items:
    - "{{ ansible_facts.packages.keys()|list | map('regex_search', v_debian['exclusions']) | select('string') }}"
  tags:
    - fullupgrade
    - install

- name: "postinstall | debian | apt | perform full upgrade"
  apt:
    upgrade: full
  environment:
    ACCEPT_EULA: y
  tags:
    - fullupgrade

- name: "postinstall | debian | apt | perform upgrade without kernel"
  apt:
    upgrade: safe
  environment:
    ACCEPT_EULA: y
  tags:
    - safeupgrade
