---
- name: "Postinstall | Debian | Apt | Update local cache"
  tags:
    - always
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 7200

- name: "Postinstall | Debian | Apt | Get packages facts"
  tags:
    - always
  ansible.builtin.package_facts:

- name: "Postinstall | Debian | Apt | Lock kernel packages"
  with_items:
    - "{{ ansible_facts.packages.keys() | list | map('regex_search', v_debian['exclusions']) | select('string') }}"
  tags:
    - safeupgrade
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: hold

- name: "Postinstall | Debian | Apt | Unlock kernel packages"
  with_items:
    - "{{ ansible_facts.packages.keys() | list | map('regex_search', v_debian['exclusions']) | select('string') }}"
  tags:
    - fullupgrade
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: install

- name: "Postinstall | Debian | Apt | Perform full upgrade"
  environment:
    ACCEPT_EULA: y
  tags:
    - fullupgrade
  ansible.builtin.apt:
    upgrade: full

- name: "Postinstall | Debian | Apt | Perform upgrade without kernel"
  environment:
    ACCEPT_EULA: y
  tags:
    - safeupgrade
  ansible.builtin.apt:
    upgrade: safe
