---
- name: "Install debian specific packages"
  tags:
    - install
    - lm_install
  block:
    - name: "Postinstall | Debian | pkg_install | Install disk tools collection"
      ansible.builtin.apt:
        name: "{{ v_debian['disk_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"

    - name: "Postinstall | Debian | pkg_install | Install network tools collection"
      ansible.builtin.apt:
        name: "{{ v_debian['net_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"

    - name: "Postinstall | Debian | pkg_install | Install security tools collection"
      notify: "Restart auditd"
      ansible.builtin.apt:
        name: "{{ v_debian['security_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"

    - name: "Postinstall | Debian | pkg_install | Install system tools collection"
      ansible.builtin.apt:
        name: "{{ v_debian['sys_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"
