---
- name: "install debian specific packages"
  block:
    - name: "postinstall | debian | pkg_install | install disk tools collection"
      ansible.builtin.apt:
        name: "{{ v_debian['disk_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"

    - name: "postinstall | debian | pkg_install | install network tools collection"
      ansible.builtin.apt:
        name: "{{ v_debian['net_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"

    - name: "postinstall | debian | pkg_install | install security tools collection"
      ansible.builtin.apt:
        name: "{{ v_debian['security_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"
      notify: restart auditd

    - name: "postinstall | debian | pkg_install | install system tools collection"
      ansible.builtin.apt:
        name: "{{ v_debian['sys_pkg'] }}"
        state: present
        dpkg_options: "{{ v_debian['dpkg_opts'] }}"

  tags:
    - install
