---
- name: "install rhel specific packages"
  block:
    - name: "postinstall | rhel | pkg_install | enable EPEL repository"
      ansible.builtin.yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: "postinstall | rhel | pkg_install | install dnf"
      ansible.builtin.yum:
        name:
          - dnf
        state: present

    - name: "postinstall | rhel | pkg_install | install disk tools collection"
      ansible.builtin.dnf:
        name: "{{ v_rhel['disk_pkg'] }}"
        state: present

    - name: "postinstall | rhel | pkg_install | install security tools collection"
      ansible.builtin.dnf:
        name: "{{ v_rhel['security_pkg'] }}"
        state: present
      notify: restart auditd

  tags:
    - install
