---
- name: "Install rhel specific packages"
  tags:
    - install
  block:
    - name: "Postinstall | RHEL | pkg_install | Enable EPEL repository"
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: "Postinstall | RHEL | pkg_install | Ensure dnf is present"
      ansible.builtin.dnf:
        name: dnf
        state: present

    - name: "Postinstall | RHEL | pkg_install | Install disk tools collection"
      ansible.builtin.dnf:
        name: "{{ v_rhel['disk_pkg'] }}"
        state: present

    - name: "Postinstall | RHEL | pkg_install | Install security tools collection"
      notify: "Restart auditd"
      ansible.builtin.dnf:
        name: "{{ v_rhel['security_pkg'] }}"
        state: present
