---
- name: "Postinstall | RHEL | subscription | Attach rhel server to redhat subscription manager"  # noqa no-changed-when
  ansible.builtin.raw: "subscription-manager register --username {{ rhel_subscription_user }} --password {{ rhel_subscription_pass }} --auto-attach"
  tags:
    - install

- name: "Postinstall | RHEL | subscription | Manage subscription"
  community.general.redhat_subscription:
    state: present
    username: "{{ rhel_subscription_user }}"
    password: "{{ rhel_subscription_pass }}"
    auto_attach: true
    force_register: "{{ rhel_subscription_force }}"
  tags:
    - subscription
