---
- name: "Postinstall | RHEL | Yum | Perform full upgrade"
  tags:
    - fullupgrade
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true

- name: "Postinstall | RHEL | Yum | Perform upgrade without kernel"
  tags:
    - safeupgrade
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true
    exclude:
      - "{{ v_rhel['exclusions'] }}"

- name: "Postinstall | RHEL | Yum | Perform security and bugfix update"
  tags:
    - bugsecupgrade
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true
    bugfix: true
    security: true
    exclude:
      - "{{ v_rhel['exclusions'] }}"
