---
- name: "Postinstall | RHEL | Yum | Update local cache"
  ansible.builtin.yum:
    update_cache: true
  tags:
    - always

- name: "Postinstall | RHEL | Yum | Perform full upgrade"
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true
  tags:
    - fullupgrade

- name: "Postinstall | RHEL | Yum | Perform upgrade without kernel"
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true
    exclude:
      - "{{ v_rhel['exclusions'] }}"
  tags:
    - safeupgrade

- name: "Postinstall | RHEL | Yum | Perform security and bugfix update"
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true
    bugfix: true
    security: true
    exclude:
      - "{{ v_rhel['exclusions'] }}"
  tags:
    - bugsecupgrade
